wafflestudio/csereal-server

- build.gradle.kts
- src/main/kotlin/com/wafflestudio/csereal/common/config/CserealExceptionHandler.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeTagEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeTagRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/CreateNoticeRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/UpdateNoticeRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/resources/application.yaml
공지사항 수정, 삭제, 태그
ExceptionHandler, updateNotice, deleteNotice, Tag 엔티티, noticeTag 연관 엔티티 추가
[068225a]: 예외가 나올 때 처리하는 기능을 추가했습니다. @Valid로 인해 오류 떴을 때 메시지 전송 / csereal 내부 규정 오류 /  db에서 중복된 값 있을 때 나오는 예외를 처리했습니다.
[8d8d5cd]: 공지사항을 수정하는 기능을 추가했습니다. _@Valid을 통해 제목이 빈칸이거나, 내용이 빈칸이면 오류 메시지가 뜨도록 했습니다._ -> 확인해보니 내용을 ""으로 전송해도 전송이 잘 되네요.. 이거는 다음 pr에 수정하도록 할게요. NoticeEntity에서 isPublic 등의 기타 칼럼을 추가했습니다 
[0382376]: 공지사항을 삭제하는 기능을 추가했습니다. soft_delete 방식을 적용하여서, 삭제할 때 db 상에서 없어지는 게 아니라 isDeleted = true가 되도록 했습니다.
[3f2e94d]: TagEntity, NoticeTagEntity 엔티티를 추가하고, 공지사항에 태그를 추가하기 전에 우선 태그를 등록하는 기능을 추가했습니다.
[be6d433]: 공지사항을 올릴 때 태그도 같이 올리고, 수정할 때 태그도 같이 수정할 수 있도록 했습니다.
[c349869]: 혼자서 만들때는 로컬 db에 연결해서 하는데, 깜박하고 안 없앴네요. 다시 없는 상태로 올렸습니다.
@Valid 메시지가 적용되도록 할 것. 다음으로는 페이지네이션 생각 중
+) (07/26 12:49) @Valid 잘 되도록 했습니다 …
> feat: 공지사항 수정, 삭제, 태그 기능 추가

- src/main/kotlin/com/wafflestudio/csereal/common/Exceptions.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/CareerEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/EducationEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ResearchAreaEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/dto/CareerDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/dto/EducationDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/dto/ProfessorDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/dto/SimpleProfessorDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/LabEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/LabRepository.kt
교수 엔티티 설계 및 API 구현하였는데 LabEntity는 미완성이고 학력, 경력, 연구 분야는 교수에만 종속적인 것 같아서 임의로 구현해보았습니다. 
[e63a6cc35065ce17dae25e558232c8018f03ddc1]: 교수 엔티티 및 DTO 설계
[25ab76056f4b801245fcffc1483a3686721306ec]: 교수 생성 및 조회 API 구현
이미지 업로드 구현
> feat: 구성원(교수) 생성 및 조회 API 구현 

- build.gradle.kts
- src/main/kotlin/com/wafflestudio/csereal/common/config/QueryDslConfig.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/CreateNoticeRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/SearchDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/SearchRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/SearchResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/UpdateNoticeRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/resources/application.yaml
페이지네이션+검색 기능 추가
태그와 키워드를 이용한 공지사항 검색이 가능하고, 페이지네이션을 통해 페이지에 맞게 원하는 만큼을 보여줄 수 있습니다. (원래는 한페이지에 게시글 20개, 지금은 코드상 5개)
PR 요약해주세요
[ecb4513]: 엔티티에서 isPublic, isSlide, isPinned 칼럼을 생성했습니다.
[9443b7a]: queryDsl gradle을 도입하기 위해 implement와 kapt을 추가했습니다. 또한 spring 3.0부터는 javax를 jakarta로 바꿔야 한다고 해서 바꿨습니다. 각각 https://onethejay.tistory.com/197 와 https://covenant.tistory.com/279 을 참고했습니다.
[cb2e22b]: queryDsl을 실제로 도입하기 위해 JPAQueryFactory을 가져왔습니다.
[832e0f9]: 태그와 키워드를 입력하면, id/제목/날짜/list<태그>가 나오도록 했습니다. (태그 리스트는 로컬 테스트할 때 자주 써서 넣었습니다.) 태그를 여러개 입력하면 여러 태그 중 하나라도 만족하면 들고오도록 했고, 키워드는 제목이나 본문에서 포함하면 들고오도록 했습니다. 태그만 입력/키워드만 입력/태그+키워드 입력 모두 가능합니다. 음.. 일단 구현은 되는데, 혹시 쿼리 최적화 등에 대해 필요해보인다면 리뷰 부탁드려요.
[10ac208]: 쿼리에서 isDeleted = false, isPublic = true인 게시글만 나오고, 최신순 중에서 isPinned =true인 것들이 가장 위에 나오도록 했습니다.
[3e2b0ad]: …
> feat: 페이지네이션+검색 기능 추가

- src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/TaskEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/dto/StaffDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
교수 API와 거의 동일하게 행정직원 엔티티 설계 및 API 개발하였습니다.
[0f18287e01d1fb62dc1ee92b583163c4d1dd0a7a]: 엔티티 및 DTO 설계
[1d4d2283ee4a828eabe3b40ca77dee4f4834dfcd]: CRUD API
[8d272a54f421d7c4d1480b39fc51ca7b091d7420]: 교수 조회 시 이름순 정렬 (행정직원 조회 만들다 생각나서 추가)
[e2f94ce1b825836806d5006a60e0014aa263fbc9]: 교수 연구분야 Set->List 변경 (행정직원 주요 업무 만들다 연구 분야도 중요도별 순서가 있을수 있나 싶어 List로 변경하였습니다
[c4f1f7efc51465344b1556d5c4116b0bb4d22d78]: 행정직원 주요업무 업데이트 구현
로그인 구현
> feat: 구성원(행정직원) CRUD API

- Dockerfile
Dockerfile에서 $Profile이 environment variable로 대체되지 않고 그대로 string으로 들어가는 문제가 있어, 배포되었을 시 제대로 profiile 적용이 되지 않는 현상이 있었습니다.
4bfadc27d8185c87c106b45e5cd6694c57497004: Entrypoint를 String list가 아닌 하나의 string으로 하여 variable의 대체가 잘 일어나도록 하였습니다.
> [Hotfix] Fix Dockerfile

- src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutPostType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsPostType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsStudentType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/CourseEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/CourseRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/StudentType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionPostType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsPostType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/StudentType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/dto/AdmissionsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/NewsResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/NoticeResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
fix: about, academics, admissions 패키지 수정
세 패키지에서 api 주소를 바꾸고, 각각의 패키지에 postType을 추가했습니다. 
[9d33d4a] , [b6fb6f4]: 두 패키지에서 한 게 거의 같아서 합치겠습니다
주소를 정한 규칙이 화요일에 준형이랑 얘기한 거랑도 달라지고, 프론트에게 전달되는 것도 많이 바뀌는 규칙이라서 설명드리겠습니다.
규칙은 postType을 enum으로 따로 두고, studentType은 그냥 string으로 두기로 했습니다
또한 postType은 requestParam으로 받고 about, admissions 같은 대항목이나 studentType은 pathVariable로 받고 있습니다
가장 마지막 항목 전까지는 /로 받고, 가장 마지막 항목이 세부항목들로 갈리면 postType(requestParam)으로 받도록 했습니다.
이러한 규칙으로 나머지 패키지 모두 바꿀 예정입니다.
만약 개선했으면 하는 점, 혹은 반대하는 점이 있다면 pr로 리뷰 부탁드려요
이러한 규칙을 적용하게 되면 프론트도 변경점이 상당하기 때문에 빨리 메인까지 pr로 보내야 할 거 같아요.
제 계획은, 일부 패키지 수정한걸로 백에서 허락 맡고, 얘를 develop으로 pr하고,  나머지 패키지를 합의된 규칙으로 바꾸고, 다시 develop으로 pr해서, 한번에 프론트에게 통일된 규칙을 전달하고 싶습니다.
원래는 모든 패키지를 한번에 pr하는 것도 생각했지만, 그렇게 패키지에 많은 점이 변경되면 리뷰가 배로 느려진다는 것을 저번주에 알게 되어서요. 절반만 보내드려요.
만약 리뷰가 …
> fix: about, academics, admissions 패키지 수정

- docker-compose.yml
https 적용 테스트를 위하여 배포 port를 8080으로 변경합니다.
68fb5bf074706ec78e235d185583eb406a02838c: [CICD: Change deploy port to 8080](https://github.com/wafflestudio/csereal-server/commit/68fb5bf074706ec78e235d185583eb406a02838c)
> Test: Deploy to 8080

- src/main/kotlin/com/wafflestudio/csereal/common/controller/AttachmentContentEntityType.kt
- src/main/kotlin/com/wafflestudio/csereal/common/controller/ImageContentEntityType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/api/AttachmentController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/dto/AttachmentDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/dto/AttachmentResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/database/MainImageEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
- src/main/resources/application.yaml
feat: attachments 패키지 추가, news와 seminar request에 attachments 추가
image 하는 것에서 attachments 버전을 추가시켰습니다. 첨부파일은 대부분의 패키지에 들어가야 하는데 그중에서 news, seminar을 올려요
PR 요약해주세요
[33d20e0]: attachments 패키지를 추가했고, news에서 attachments를 추가할 수 있도록 했습니다.
[3149e2d]: seminar에서 attachments를 추가할 수 있도록 했습니다.
[c47e1ad]: mappedBy 추가했습니다.
[18152d2]: 경로 분리했습니다.
공지사항, academics 등등에서 다 추가할 수 있도록 해야죠
> feat: attachments 패키지 추가, news와 seminar request에 attachments 추가

- src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferencePageEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferencePageRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferencePage.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceService.kt
Conference 엔티티에 개별 항목 정보를 저장하고 ConferencePage에서 생성/수정일, 저자와 함께 Conference 리스트를 응답하도록 구성하였습니다.
[7b43b86b0c8ff8aad73a97e8386f911fde617257]: GET API
[d732a589584ca33f7ea1f6fc95afbaf2e545c126]: DB에서 가져올때 정렬
> feat: Top Conference List GET API

- src/main/kotlin/com/wafflestudio/csereal/common/controller/MainImageContentEntityType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/AcademicsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/LabEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/LabDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/LabProfessorResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchLabResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/introductionMaterial/dto/introductionMaterialDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
fix: research 패키지 프론트에 맞춰 협의
research 패키지에서 프론트에서 요구하는 request을 맞췄으며, 이를 위해 mainImage와 첨부파일을 추가했습니다.
첨부파일은 원래는 없는데, 혹시나 필요할 수도 있어서 추가했습니다
[a1783da]: professor, staff의 update에서도 mainImage 등록이 가능하도록 추가했습니다.
[069212e]: research에서 isPublic을 제거했고, lab에도 첨부파일을 추가할 수 있도록 했습니다. 
[70c9e37]: 저번에 반영하라고 했던 attachmentResponses가 안보여서, 다시 반영했습니다. attachmentResponses는 null이 아니라 빈리스트를 반환하도록 했습니다.
[bda70ef]: 프론트의 request을 보니 교수님에서 id와 name을 같이 요구해서 그렇게 수정했습니다.
[b52619f]: lab은 첨부파일이 list가 아니라 단일항목이었습니다. 이걸 그냥 request는 list로 하고 단일항목만 제시할지, 아니면 request도 단일항목으로 할지 많이 고민했는데, lab에서는 request가 항상 하나일 거 같아서 단일항목으로 하도록 했습니다. uploadAttachments도 하나만 보낼 수 있도록 uploadAttachmentInLabEntity를 따로 만들었습니다. 단일항목을 받는게 labEntity 말고 하나가 더 생기면 contentEntityType을 추가할 거 같은데, 아직은 하나라서 labEntity를 받도록 했습니다.
[af19681]: 프론트의 요구조건을 보니 개별 …
> fix: research 패키지 프론트에 맞춰 협의

- Dockerfile
- docker-compose-backend.yml
[c976e84bc317a8073526b6f924318ffdddc8b309]: [CICD: Add mainImage, attachment directory for mounting](https://github.com/wafflestudio/csereal-server/commit/c976e84bc317a8073526b6f924318ffdddc8b309)
[d01df3a8c4e3d0512addcce5ae9dcb5457b487fd]: [CICD: Add volumes to mount with server directory. (for attachment)](https://github.com/wafflestudio/csereal-server/commit/d01df3a8c4e3d0512addcce5ae9dcb5457b487fd)
> [CICD] mainImage, attachment 경로 mount 설정

- src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReserveRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
예약 GET API 응답에 지도교수, 반복 횟수를 추가하였습니다. 반복 횟수는 처음 설정한 횟수이고 개별 삭제에 따른 변경은 없습니다.
[df3516d7a7d3d05ba3e44b4856728273fd300498]: 예약 응답 수정
> fix: 예약 dto에 지도교수, 반복 횟수 추가

- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
[`fe64775d26a5c30d7cc4949eb31f5264b160aa78`]: [Fix: Change notice and news entity description type as TEXT.](https://github.com/wafflestudio/csereal-server/commit/fe64775d26a5c30d7cc4949eb31f5264b160aa78)
서버 DB는 제가 수동으로 수정하였습니다.
> [Fix] Notice, News Description TEXT type으로 변환

- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsSearchDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarSearchDto.kt
fix: newsSearchResponse, seminarSearchResponse 수정
newsSearchResponse, seminarSearchResponse을 프론트가 원하는 정보로 수정했습니다.
PR 요약해주세요
[42bf4afc10c4164494cd762447e0ab6e656a5c5b]: newsSearchResponse에서 imageURL을 추가했고, 태그를 이름으로 바꿨습니다.
[bf94c43c7d21892ddae2fdd132473dcfe97584e6]: SeminarSearchResponse에서 imageURL과 description을 추가했습니다. 원래 백에서 글자수를 짧게 해달라고 들었는데, 프론트에서 딱히 그런 이야기가 없어서 풀로 보내드리고, 이름을 summary에서 clean으로 바꿨습니다.
원래 fix_with_front3을 만들다가, news와 seminar 전체목록을 알려달라고 해서 이걸 먼저 만들었습니다. 지금 3에서는 학사 및 교과와 관리자 페이지를 만들고 있습니다.
> fix: newsSearchResponse, seminarSearchResponse 수정

- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsSearchResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeSearchResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarSearchResponse.kt
프론트에서 공지사항 GET이 너무 느리다는 얘기가 있어서(4초가 넘음) total 쿼리를 갯수만 가져오도록 해보았습니다. 실제로 어느정도 성능 이점이 있을지는 배포 후 테스트 해봐야 할것 같습니다.
[aa10834605cfef10a5c85cc41e5c546d2cdc0256]: 쿼리 최적화
> fix: total 쿼리 최적화

- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
seminar 테이블의 additional note의 경우 길어지는 데이터가 존재하여 TEXT type으로 변경합니다.
[`fb68ba97be8abbbd959d1d0e7b3b3df0704f1443`]: [Fix: Change type of additionalNote column on SeminarEntity to "TEXT"](https://github.com/wafflestudio/csereal-server/commit/fb68ba97be8abbbd959d1d0e7b3b3df0704f1443)
> Fix: additional note column type to text

- src/main/kotlin/com/wafflestudio/csereal/common/Utils.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
Notice description을 create, upate 시에 html 태그를 지운 clean text를 db에 저장 및 업데이트 하도록 변경하였습니다.
2232c09 Feat: Add plainTextDescription.
6c76291 Feat: Add plainTextDescription in createNotice.
b4b8682 Feat: add updating plainTextDescription when updating description.
> Feat: Add plain text description for notice

- src/main/resources/application.yaml
- src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
[b7491c5](https://github.com/wafflestudio/csereal-server/pull/78/commits/b7491c515bac095586027b95195661d606cd7957): Test: Add Tests for Create, Update Notice, in perspective of plainTextDescription
[51b84d6](https://github.com/wafflestudio/csereal-server/pull/78/commits/51b84d648c1b5010518002e5001b4fe6271a0ce0): [Fix: Change life cycle hook resolution to container.](https://github.com/wafflestudio/csereal-server/pull/78/commits/51b84d648c1b5010518002e5001b4fe6271a0ce0)
> [Test] Notice create, update 시 plainTextDescription 동작 테스트

- src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
- src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/member/service/StaffServiceTest.kt
구성원 검색을 위한 테이블을 추가하고, 교수와 행정직원의 create/update에도 해당 테이블을 같이 수정하도록 하였습니다.
2f4c97d Feat: MemberSearchEntity 추가.
e7f7686 Feat: MemberSearchRepository 추가
baa9adc Feat: MemberSearchService 추가
5ccb4f1 Feat: ProfessorEntity, StaffEntity에 MemberSearch 추가.
09248a9 Feat: ProfessorStatus에 한글 값 추가.
5c47654 Feat: professor create, update 시 memberSearch도 반영하도록 추가.
2d05ae2 Feat: seminar create, update 시 memberSearch도 반영하도록 추가.
ff1b8f1 Test: ProfessorService 테스트 추가.
b5932bb Test: StaffServiceTest 추가.
MemberSearchEntity를 이용한 검색 구현.
> Feat: 구성원 검색 위한 table 추가.

- src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainImportantResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainNoticeResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainSlideResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/NoticesResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagInNoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagInNoticeEnum.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagInNoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
fix: main 프론트에 맞게 협의, notice 태그 enum 추가
mainResponse을 프론트가 원하는 바에 따라 고쳤고, notice에서 태그들을 enum으로 추가시켰습니다.
[73b195a248fadce79bfd4a85d3b38010afd61bbf]: 프론트에서 메인을 slides, notices, importants로 주기를 원해서 맞게 고쳤습니다.
[c2ddb16540295d6d5c55bcb0b7504c6f6bd2370f]: notice Tag들을 프론트에서 제공하는 목록 그대로 가져왔습니다.
[015353473c50c22500d1db96a1678f58fb18d9a3]: tagEnum을 update, main 등에서도 잘 쓸 수 있도록 들고왔습니다.
News 태그를 손봐야 하고, 소개에서 차트도 봐야 합니다
질문이 있는데, 저희 검색을 위해 pageName 넣기로 한거 아직 그대로죠?
> fix: main 프론트에 맞게 협의, notice 태그 enum 추가

- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/TagInNewsEnum.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagInNoticeEnum.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
공지 태그 응답을 한국어로 수정 및 공지,새소식 태그를 리팩토링하였습니다.
[796966d8e4001183f721a4ee5a252b77725a859e]: 공지 태그
[4d56af023a030e7cb050269e63b3c7bd8c3bff5d]: 새소식 태그
> refactor: 공지 태그 응답 한국어로 변경 및 리팩토링

- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
세미나에 적용했던 로직 동일하게 공지 새소식에도 적용하였습니다 
[e47cf8a81901ff003d404e9f359180e194dc431d]: fix PATCH api
예약 쪽 권한 수정
> fix: 공지 새소식 PATCH 로직 수정

- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
프론트에서 다음 페이지 버튼을 위해 total 더미 값 수정하고 pageNum null 일때만 더미 값 주도록 변경하였습니다 (1페이지 버튼 눌러도 total값 제대로 주게끔)
[cad8cade214ad4d8ffb6f5db2bdb54cd46a1229e]: total 값 관련 수정
> fix: total 더미 값 + pageNum null일때만 더미 값 주기

- src/main/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservceController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/SimpleReservationDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
관리자가 아닌 예약 권한이 있는 다른 사용자들도 유저 정보를 제외한 응답을 볼 수 있게 수정하였습니다.
월별,주별 조회 응답용 SimpleReservationDto 클래스를 별도로 생성하였습니다.
[16c312810335f8cfa87ea85a6042f62d57674061]: 예약 단건 조회 권한 분리
[edcf673c868113ba706d4a7d9925e8e80c08d558]: SimpleReservationDto
> fix: 예약 조회 권한 분리 및 응답 단순화

- src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/CompanyEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/StatEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/AboutRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FutureCareersCompanyDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FutureCareersRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FutureCareersResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FutureCareersStatDegreeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FutureCareersStatDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/request/AboutRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/request/FutureCareersRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
feat: migrateAbout, migrateFutureCareers 추가
about 패키지에서 migrateAbout, migrateFutureCareers를 추가했고, 관련 request을 추가했습니다.
[2f2bba73d50b83bd4dbdb795bbbe2a1df41af06d]: migrateAbout 메서드를 만들었고, 패키지에 대해서 request를 따로 만들었으면 좋겠다고 해서 AboutRequest을 따로 만들었습니다. 나중에는 createAbout의 AboutDto도 AboutRequest로 만들 수 있게끔 만들었습니다.
[f2dc552c2b24ebdd6900780256e2a99def7e4b61]: migrateFutureCareers 메서드를 만들었고, request와 dto를 만들었습니다.
CompanyDto, CompanyNameAndCountDto가 FutureCareersCompanyDto와 FutureCareersStatDegreeDto와 거의 유사한데, 만약 이번 pr이 통과되면 CompanyDto, CompanyNameAndCountDto는 뒤의 두개로 변경할 예정입니다
[[c00821b](https://github.com/wafflestudio/csereal-server/pull/118/commits/c00821b163f539e6e13dd1fe1a2502238cb355b1)]: AboutRequest는 개요, 인사말, 연혁에만 적용되는 것들입니다. 그런데 불필요한 request들이 많아서 다른 것들은 잘랐습니다.
같은 About 패키지라고 하더라도 요청하는 값이 다르면 …
> feat: migrateAbout, migrateFutureCareers 추가

- src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainImportantResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarServiceTest.kt
fix: news, notice에 titleForMain 추가
news와 notice에 titleForMain을 추가하였고, 메인 중요안내에서 이들이 제목으로 나오게 했으며, description을 추가하였습니다.
main에서 title은 그쪽에서 title로 받고 있었으니까 굳이 titleForMain으로 안 바꿨고,
커밋에서는 삼총사라도 적어놨는데 실제로는 새소식과 공지사항만 titleForMain을 받기를 원하셔서 두개만 고쳤습니다
> fix: news, notice에 titleForMain 추가

- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarServiceTest.kt
삭제할 첨부파일 id목록을 request 내부에서 받도록 변경하였습니다.
[fce1c48fe32de8c6a5128d7ff68d0edb4ea71fb8]: 리팩토링
> refactor: deleteIds request 내부로 이동

- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsSearchDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarSearchDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
관리자만 목록에서 비공개 글 확인 가능하도록 하였습니다.
[88d5f13a8386f973b682cd002389b933216700ad]: 커스텀 레포에 isPrivateBooleanBuilder 추가 + 응답에 isPrivate 추가
> feat: 관리자는 새소식, 세미나 목록에서 비공개 글 확인 가능

- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
> Hotfix: Fix search total notice stringLength default value.

- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/test/kotlin/com/wafflestudio/csereal/core/news/NewsServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/news/NewsServiceTest.kt
뉴스를 createdAt 대신 date로 정렬하도록 하였고, date를 non null하게 바꾸었습니다.
46dd7b7 Feat: Change date field to NOT NULLABLE.
a4d2e31 Feat: Change to sort by date, not createdat.
cb7ce9f Test: Fix test.
> Feat: 뉴스 날짜로 정렬

- src/main/kotlin/com/wafflestudio/csereal/core/admin/service/AdminService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
삭제된 글이 중요 안내에서 보이지 않게 하고 관리자 페이지에서는 비공개 중요 안내는 볼 수 있도록 하였습니다. 
메인 페이지에서는 최대 2개까지 중요 안내를 보내주고, plainTextDescription을 보내도록 수정하였습니다.
> fix: 중요 안내

- src/main/kotlin/com/wafflestudio/csereal/core/resource/common/api/DeprecatedFileController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/common/api/FileController.kt
첨부파일 다운로드 시 파일 이름이 이상하게 받아지는 문제가 있었는데 content-dispositon 헤더로 filename을 직접 주어서 해결하였습니다.
> fix: 첨부파일 다운로드

- src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
메인에서 6개씩 보이는 공지사항에 고정 글 여부 상관없이 최신순으로 정렬하였습니다.
[837f51707492ab4b3f1ef9cac1dabe492d117935]: 메인 공지 정렬
> fix: 메인 공지 정렬

- src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservationController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
행정실에서 개인정보 제외한 조회는 전체 공개도 괜찮다고 하여서 권한 수정을 하고, recurrenceId는 항상 보내도록 하였습니다.
[44f3aa456cd8638f27ed95d24678497e1153c494]: 권한 수정
> fix: 예약 조회 권한 수정

- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
fix: titleForMain이 없어도 isImportant 등록 가능
titleForMain = null 이어도 isImportant = true일 수 있습니다
[33c8ac4](https://github.com/wafflestudio/csereal-server/pull/160/commits/33c8ac4e8eb5a9b9b4138c9e6ea4fe677139c4f8): 지금 새소식 3총사 create할 때 isImportant = true라면 titleForMain을 작성해야 한다고 서비스 단에서 막고 있는데, 메인에 나와있는 것처럼 titleForMain이 없으면 title이 나올 수 있도록 서비스단에서의 예외조치 삭제했습니다.
TODO가 있다면 작성해주시고, 없다면 생략해주세요.
> fix: titleForMain이 없어도 isImportant 등록 가능

- src/main/kotlin/com/wafflestudio/csereal/core/admin/database/AdminRepository.kt
fix: em.close() 추가
getImportant에서 em.close()를 추가했습니다
[ff323e323548874689303efa668486fb1677934f]: 로그를 찾아보니, HikariPool에서 쓸 수 있는 pool들이 꽉 차서 안된다더라고요. 규모가 큰 거에는 pool에 대해 손을 봐야할지도 모르겠지만, 준형님 의견대로 em을 close하니 active pool 개수 바로 줄었습니다
notice 1500개 이주시키고 important get해보았을 때 아래 캡쳐 화면처럼 차이납니다
> fix: em.close() 추가

- src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferencePageEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceCreateDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/dto/ConferenceModifyRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceService.kt
- src/test/kotlin/com/wafflestudio/csereal/core/conference/service/ConferenceServiceTest.kt
feat: migrateConference 추가
migrateConference를 추가하고, createConferenceDto를 삭제하였습니다.
[bcb0ec84e0e81fc1532fb24925ec571f3e455812]: migrateConference를 추가하고, createConferenceDto가 없어도 되도록 코드를 정리했습니다.
[8874eae3b54737d2177b0589cf865893934bea40]: 소소한 수정 1
[6b0b5f308c36514145ca6fa32e271fbb461c4ffa]: 소소한 수정 2
[12bef49d0a88f8114b59bf825beb72ce2f45b5b7]: 소소한 수정 3
[0ef562e2b6e8ff379251c0df80fc21498dd0758b]: createConferenceDto를 삭제하였습니다.
> feat: migrateConference 추가

- .github/workflows/deploy.yaml
- docker-compose-backend.yml
- src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
- src/main/kotlin/com/wafflestudio/csereal/common/config/WebConfig.kt
- src/main/resources/application.yaml
id-dev가 아닌 id.snucse.org 를 가리키도록 변경하고 OIDC_CLIENT_SECRET 환경변수를 추가하였습니다.
application.yml 파일에서 local-test간 중복되는 항목이 많아 위로 합치고 prod에서 오버라이드 하는 식으로 리팩토링하였습니다.
로컬에서 따로 수정하지 않아도 로그인 페이지가 뜨도록 하였습니다.
리버스 프록시 때문에 배포 환경에서는 CORS 걱정을 할 필요는 없어보이지만, 로컬에서 직접 프론트 백 띄워서 테스트 할 때를 위해 수정하였습니다.
> refactor: 실제 스누씨 서버 연동

- src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
- src/main/resources/application.yaml
id-dev 서버가 사라져서 로컬에서도 idsnucse로 연결했습니다.
> fix: 로컬에서도 idsnucse로 연결

- src/main/kotlin/com/wafflestudio/csereal/CserealApplication.kt
- src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/event/ProfessorCreatedEvent.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/event/ProfessorDeletedEvent.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/event/ProfessorModifiedEvent.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchSearchPageResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchSearchResponseElement.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/ResearchSearchTopResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchSearchService.kt
- src/main/resources/application.yaml
- src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchSearchServiceTest.kt
feat: Research 검색
Research 검색 기능을 추가하였습니다
(HEAD)
a5863e0  Test: Fix test.
847bc05 Feat: Add search api for research.
5e9b571 Fix: fixed event listener logic
897e3e5 Test: ResearchSearchService listen professor event
634f0e9 Feat: Update research search when listen professor event.
bc13765 Feat: Publish event on professor modification.
c909984 Feat: create professor event.
970fe85 feat: enable async.
(BEGIN)
- Event 를 publish하고 listen하는 방식으로 professor가 수정될 시 lab의 search를 위해 생성한 텍스트 데이터를 업데이트 하도록 구성하였습니다.
- mysql에 researchsearch 테이블에 full text index가 생성되어있지 않은 경우 생성해주어야 정상 작동합니다.
```mysql
ALTER TABLE research_search ADD FULLTEXT INDEX research_search_idx (content) WITH PARSER ngram;
```
- lab update시 해당 lab의 research는 업데이트 되지 않도록 되어있습니다. 이 기능이 필요하다면 논의를 통해 도입해야 할 듯 싶습니다.
> feat: Research 검색

- src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
feat: staff 마이그레이션 검색인덱스도 추가
staff 마이그레이션할 때 검색 인덱스도 추가하도록 했습니다
[bfaee72]: 마이그레이션 준비 중입니다. staff 추가할 때 member_search 테이블에 행정직원 내용이 추가되도록 하였습니다.
다른 테이블에도 search 반영하려고 하고 있고, 필드에 language 추가해서 같은 테이블에 한국어판, 영문판에 따라 ko, en 넣으려고 합니다
> feat: staff 마이그레이션 검색인덱스도 추가

- src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/req/AdmissionMigrateElem.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/req/AdmissionReqBody.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsPostType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/dto/AdmissionsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/dto/AdmissionsRequest.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/type/AdmissionsMainType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/type/AdmissionsPostType.kt
- src/test/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsServiceTest.kt
Refactor: Admission 리팩터링 진행
- language column 추가
- mainType을 추가하여 (graduate, undergraduate, international) 추후 변경에 대해서도 쉽게 변경 가능하도록 하고 중복되는 method를 줄였음
- Request body를 따로 추가하여 API의 명확도를 올림
- 기존 API와 큰 차이를 가지지 않도록 고려하였음.
dfe4654 Feat: Move type to type dir, and add main type enum.
0e5cd6e Refactor: Add request body for create, and changed migrate elem body.
4d49b2b Feat: Change pagename -> name, add language and mainType column, add unique constraints.
b244133 Refactor: Remove unused request dto.
62d3556 Refactor: Change AdmissionsDto by adding columns, to be able to used as pure dto.
84d86dd Feat: Change to more specific search query.
05c2e3d Feat: Change multiple methods to few methods, by using mainType.
b1897a4 Feat: Change to few controller by using mainType, and use request bodies …
> Refactor: Admission 언어 추가 및 리팩터링 진행

- src/main/kotlin/com/wafflestudio/csereal/common/mockauth/DevAuthController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservationController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/user/api/UserController.kt
몇몇 컨트롤러에서 AuthenticationPrincipal 어노테이션을 이용해서 OidcUser를 바로 주입받는 방식을 사용했었는데, 로그인 모킹 이후 이 부분이 바이패스가 안돼서 Authentication 객체를 주입받고 principal 타입에 따라 로직을 분기 처리하도록 수정 하였습니다.
> fix: 인증 로직 수정

- src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt
fix: migrateConferences에서 authenticatedStaff 삭제
migrateConferences에서 authenticatedStaff 삭제
[02c8c5491fb5f6e8845b40e5974b5b4b7f665b6f]: Migrate에 불필요한 authenticatedStaff 삭제했습니다(다른 마이그레이션은 로그인 인증 안하고 있어서..)
> fix: migrateConferences에서 authenticatedStaff 삭제

- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
61fe801 Feat: Add FindByIdAndIsPrivateFalse
eee190a Fix: Change totalSearchNotice to get isStaff and hide private when not a staff.
1dc88d8 Fix: Change searchTotalNotice and readNotice to consider isStaff.
2562079 Fix: Change totalSearchNotice and readNotice to check authentication and get staff info.
> Fix: Notice 비밀글 표시 안되도록 수정

- src/main/kotlin/com/wafflestudio/csereal/core/research/api/res/ResearchSearchResElement.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchPostType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt
- src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt
- RESEARCH를 RESEARCH_CENTER, RESEARCH_GROUP, RESEARCH_LAB으로 세부화하였습니다.
- 사용하지 않는 LAB 관련 코드를 제거하였습니다.
2608d03 Refactor: Remove unused method
66eecef Comment: Add comment
70e6385 Feat: Add specific research types to enum
3f7d0b4 Feat: Change to give more specified enum when it is research related column.
[0527a99](https://github.com/wafflestudio/csereal-server/pull/218/commits/0527a998bd4b5fb6a497f0669f8cefa8d75ceb44) [Refactor: Remove unused LAB entry from Research.](https://github.com/wafflestudio/csereal-server/pull/218/commits/0527a998bd4b5fb6a497f0669f8cefa8d75ceb44)
> Feat: Research 검색 결과 research 타입 상세화

- src/main/kotlin/com/wafflestudio/csereal/core/research/dto/LabDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
fix: pdf 타입 AttachmentResponse로 변경
pdf 타입 AttachmentResponse로 변경
[bf154df3b8d6b6168c1347fbc0e9c04c64fdf4a9]: 엔티티의 pdf는 그대로 놔두고, dto의 pdf를 attachmentResponse 타입으로 바꿨습니다
> fix: pdf 타입 AttachmentResponse로 변경

- .github/workflows/build_and_test.yaml
- .github/workflows/deploy.yaml
- .github/workflows/ktlint-check.yml
- Dockerfile
- build.gradle.kts
- src/main/kotlin/com/wafflestudio/csereal/common/config/MySQLDialectCustom.kt
- src/main/resources/application.yaml
- Spring Boot 3.2, Java 21로 업그레이드하였습니다.
- **Java Virtual Thread**를 사용하도록 하였습니다.
- 위 설정을 적용하기 위해서 업그레이드 하였습니다.
간단하게 보자면 기존의 os 스레드와의 1:1 매칭 대신 many to many로 경량화 스레드와 매칭되도록 하여 context switch 비용을 줄이는 기술입니다.
- 근데 로컬에서 간단하게 테스트했을때는 속도만 봤을때는 오히려 살짝 느린거 같긴 해서 적용할지 고민되긴 합니다... 이부분 피드백 부탁드립니다.
- 참고링크: https://spring.io/blog/2022/10/11/embracing-virtual-threads#will-your-application-benefit-from-virtual-threads
4ac8a79 Config: Update spring boot to 3.2
d9fb33c Config: Change docker jdk version to 21
5562281 Config: Revert ktlint version.
37ce54b Fix: Update deprecated method.
37fb303 COnfig: Update jdk as 21
037d74b Config: Enable java virtual thread.
> Config: Spring Boot 3.2, Java 21로 업그레이드, Virtual Thread 적용

- docker-compose-backend.yml
`docker-compose-backend.yml`에 slack 정보가 environment에 누락되어 spring boot이 정상적으로 실행되지 못하고 있어 이를 수정.
> Hotfix: 누락된 Slack 정보 compose 파일에 추가.

- src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsSearchService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/event/RefreshSearchEvent.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchSearchService.kt
- 현재 많은 요구사항과 CUD API의 부재로 인하여 db에 직접적으로 페이지를 수정하는 일이 많음.
- 원래는 CUD API를 사용하여 검색에 사용되는 field까지 적절히 update되어야 하지만 불가능한 상황
- 따라서 게시물 (notice, news, seminar)를 제외한 통합 검색에 사용되는 모든 검색 field를 update해주는 API 추가
`http GET /api/v1/search/refresh`
d90800c Feat: Add refresh search event
b6ad1ea Feat: Add api for trigger refresh search indexes.
f6d2548 Feat: Add refresh search event listener for about entity.
252d0cd Feat: Add refresh search event listener for academics entity.
d1fba44 Feat: Add refresh search event listener for admission entity.
550369d Feat: Add refresh search event listener for member entity.
653a376 Feat: Add refresh search event listener for research entity.
> Feat: 게시물 제외 통합검색에 사용되는 field들 refersh하는 API 추가

- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/CourseEntity.kt
fix: course 띄어쓰기 그대로 유지
course 띄어쓰기 그대로 유지하였습니다.
[51b6beb5257d1077ee82e5eff8ea33cf85a9c69b]: 원래 과목들 띄어쓰기를 ‘-’로 대체했었는데, 행정실에서 – 지워달라고 하기도 하고, 이제는 들어가있을 이유도 없어서 그냥 이름의 띄어쓰기 그대로 유지하면서 저장할 예정입니다.
> fix: course 띄어쓰기 그대로 유지

- src/main/kotlin/com/wafflestudio/csereal/core/about/database/StatRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
fix: stat year 2050년까지 확장
stat year 2050년까지 확장하였습니다.
[0abed42881de01642f60951b1ddf3c47e28003d9]: 이번에 졸업생 진로가 2022년, 2023년이 추가되었는데, 기존의 거는 2021년으로 하드코딩 되어있어서 그냥 연도를 2050년까지 확장하고 졸업생 진로가 저장된 연도 내역만 표시되도록 했습니다. 테스트 결과 2050년~2024년은 안나옵니다!
> fix: stat year 2050년까지 확장

- .github/workflows/database.yaml
- .github/workflows/database_dev.yaml
- .github/workflows/deploy.yaml
- .github/workflows/deploy_dev.yaml
- .github/workflows/proxy.yaml
- .github/workflows/proxy_dev.yaml
- docker-compose-backend.yml
- 각 service의 .env 파일을 분리하여 배포 순서에 따른 문제 발생 가능성을 제거하였습니다.
- prod 환경과 dev 환경의 docker image를 태그를 통해 분리하여 관리, rollback이 용이하도록 하였습니다.
PR 요약해주세요
c255786 CICD: Seperate docker image tag of prod, dev, rename env
cc1bf78 CICD: Change env name of db
2ed8ddb CICD: Change env name of proxy
> CICD: env 파일 분리, 서버 docker image tag 분리

- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeSearchDto.kt
- keyword가 없을 시 score 칸에 "0.0"을 주어서 (의미 없는 값) 오류 해결
> Fix: notice keyword가 없을 시 오류 발생 수정

- src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/DegreeRequirementsPageResponse.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
fix: readDegreeRequirements response 행정실 요구사항에 맞게 수정
readDegreeRequirements의 response를 행정실 요구사항에 맞게 수정하였습니다
[3f63ac336c6c0d4ba2413d300ffef7540f2e6072]: Description의 내용을 바꾸고, 연도별 항목이 아니라 4개의 pdf를 달아놓도록 해달라고 해서 yearList을 attachments로 바꿨습니다. 로컬 서버에서 한 결과 슬랙에 올려놓은 형식대로 잘 변경되었습니다. 실제 develop 머지는 프론트에서도 해당 response로 하는게 괜찮다고 한 이후에 이뤄질 예정입니다.
> fix: readDegreeRequirements response 행정실 요구사항에 맞게 수정

- src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
공지,세미나,새소식 세부 게시글도 포털 검색결과에 뜨게 하기 위해서 id 목록 받아오는 api 가 필요하다고 합니다.
> feat: id list api for seo

- src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/TagInNoticeEnum.kt
Refactor: 공지 태그 FOREIGN -> INTERNATIONAL
f97609d Feat: Add validation for notice search pagesize, pagenum.
ff9eb34 Refactor: Refactor Enum.values() to Enum.entries
147e744  Refactor: Change FOREIGN -> INTERNATIONAL
- 추후 krName도 database에 저장하도록 수정.
> Refactor: 공지 태그 FOREIGN -> INTERNATIONAL

- src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/main/service/MainService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
Main API에서 `importantCnt` 쿼리 파라미터를 선택적으로 전달할 수 있도록 수정하였습니다. (전달하지 않을 경우 모든 중요 공지 전달)
> Feat: Main API에서 중요 공지 갯수 optional하게 전달하도록 수정

- src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/common/event/FileDeleteEvent.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/common/service/CommonFileService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt
- MainImage, Attachment에 대하여 transaction이 완료했을 경우만 파일을 제거하는 method를 추가하였습니다.
- `CommonFileService.removeFile`이 transaction이 commit되었을 경우 event를 listen하여 주어진 경로의 파일을 제거합니다.
17a02c9 Feat: Create file delete event.
998be6c Feat: Create File Delete Event Listener, only delete file when transaction commit.
eeb765d Feat: Add remove entity method which publish file delete event.
기존 deprecated된 파일 safe delete 방식 제거.
> Feat: 안전한 파일 제거 method 추가

- src/main/kotlin/com/wafflestudio/csereal/common/config/OpenApiConfig.kt
- src/main/kotlin/com/wafflestudio/csereal/common/enums/LanguageType.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/api/req/CreateStaffReqBody.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/api/req/ModifyStaffReqBody.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/dto/StaffDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
- src/test/kotlin/com/wafflestudio/csereal/core/member/service/StaffServiceTest.kt
- 사용하지 않고 로직이 불완전했던 staff 수정 api를 수정하여 적용했습니다.
- 수정 시 파일과 검색을 위한 인덱스 역시 수정되도록 함.
- response로 사용하는 dto와 request body를 분리.
Professor에 대한 같은 작업.
> Feat: Staff 수정 API 추가

- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/UpdateGuideReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/UpdateSingleReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
학부 안내, 대학원 안내, 졸업 규정 페이지를 위한 수정 api + deleteAttachments 추가
[30f494a01f91ffd11192c12087afa542776dc6cd]: 안내 페이지
[681682e7ad8f079f7a940ec528fde721a5bc43e2]: search entity 수정
[74bd48bd99b8c307588ef97f86386169cb9b1655]: 졸업 규정
나머지 학사 및 교과 페이지를 위한 update api
> update api for single html page

- src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
strict-origin-when-cross-origin
> referrer policy 헤더 추가

- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/CreateScholarshipReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/UpdateScholarshipPageReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/UpdateScholarshipReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/v1/AcademicsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/api/v2/AcademicsController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/ScholarshipEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/ScholarshipLanguageEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/ScholarshipLanguageRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/database/ScholarshipRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
장학제도 상위 페이지 수정 api 추가, 개별 장학제도 crud v2 api
prod 나갈때 scholarship_language 테이블 생성 및 id 연결
> feat: scholarship CRUD

- src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/CreateFacReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/CreateStatReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/api/req/UpdateFacReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/api/v1/AboutController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/api/v2/AboutController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutLanguageRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FacDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/FacReq.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/dto/GroupedDirectionDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
시설, 찾아오는길 v2 GET api, 졸업생 진로 현황 연도 추가, 연도별 수정 api
> 시설, 찾아오는길 v2 read api + 진로 현황 CU api

- src/main/kotlin/com/wafflestudio/csereal/core/recruit/api/RecruitController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/recruit/api/req/ModifyRecruitReqBody.kt
- src/main/kotlin/com/wafflestudio/csereal/core/recruit/database/RecruitEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/recruit/dto/RecruitPage.kt
- src/main/kotlin/com/wafflestudio/csereal/core/recruit/service/RecruitService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt
- GET 시 db에 존재하지 않는 경우 비어있는 dto 반환하도록 수정
- PUT API를 통해 신입교수초빙 페이지 수정할 수 있도록 추가
- 내부에서는 하나의 db record를 upsert함.
- RecruitEntity에 mainImage 추가
> Feat: 신입교수초빙 수정 API 생성

- src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt
- src/main/kotlin/com/wafflestudio/csereal/core/council/database/CouncilEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/council/database/CouncilRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/council/dto/ReportDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/council/service/CouncilService.kt
- src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt
- src/main/resources/db/migration/V3__update_council.sql
CouncilEntity가 intro, report 까지 커버
소개 페이지 하나 때문에 type을 만드는게 좀 불필요하다고 생각해서 repository를 보면 title이 intro 인걸 제외하도록 되어있는데 id가 바뀔일이 없을거라 db 레코드 만든 후에 id 제외하도록 하는게 나을 것 같기도 한데 의견 부탁드립니다.
> 학생회 활동보고 crud

- src/main/kotlin/com/wafflestudio/csereal/common/repository/CommonRepository.kt
- full text 시 keyword로 넣어주는 값에 연산자를 공백으로 변환한 후 전달하도록 수정하였습니다.
- 검색 시 `@`를 입력하는 경우 sql 오류 발생 (해당 연산자는 뒤에 숫자가 반드시 붙어야 함)
- 현재 고급 검색을 지원하고 있지 않으므로, `@`를 포함한 연산자를 공백으로 변환 후 query를 하도록 수정함.
- https://dev.mysql.com/doc/refman/8.4/en/fulltext-boolean.html
> fix: replace operators to space in mysql full text search

- src/main/kotlin/com/wafflestudio/csereal/CserealApplication.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/scheduler/NoticeScheduler.kt
- src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt
- src/main/resources/db/migration/V9__add_notice_expiration_dates.sql
- src/test/kotlin/com/wafflestudio/csereal/core/notice/scheduler/NoticeSchedulerTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeServiceTest.kt
기존의 공지사항 고정(`isPinned`) 및 중요(`isImportant`) 표시는 영구적이었습니다. 운영상 특정 기간 동안만 해당 상태를 유지해야 하는 요구사항을 충족하기 위해, 고정 및 중요 상태에 만료 기한을 설정하는 기능을 추가합니다.
1.  **데이터베이스 및 모델 변경:**
*   `notice` 테이블 및 `NoticeEntity`에 만료 날짜를 저장하기 위한 `pinned_until` (DATE, nullable), `important_until` (DATE, nullable) 컬럼/필드를 추가했습니다. (Flyway 마이그레이션 `V9`)
*   `NoticeDto`에도 해당 `LocalDate?` 타입 필드를 추가하여 API 요청 및 응답에 포함될 수 있도록 했습니다.
2.  **생성/수정 로직 변경:**
*   `NoticeService`의 공지 생성(`createNotice`) 및 수정(`NoticeEntity.update`) 로직을 수정하여 `isPinned`/`isImportant` 플래그와 함께 만료 날짜(`pinnedUntil`/`importantUntil`)를 설정할 수 있도록 했습니다.
*   사용자 요청 시 `isPinned`/`isImportant` 플래그가 우선시됩니다. (예: `isPinned=false`로 요청 시 `pinnedUntil` 값은 무시되고 `null`로 저장됨)
3.  **자동 만료 처리 (스케줄러):**
*   매일 새벽 1시(KST)에 실행되는 `NoticeScheduler`를 추가했습니다.
*   이 스케줄러는 `NoticeRepository`의 …
> feat: 공지글 고정 & 메인 만료기간 추가

- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/news/scheduler/NewsScheduler.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt
- src/main/kotlin/com/wafflestudio/csereal/core/seminar/scheduler/SeminarScheduler.kt
- src/main/resources/db/migration/V10__add_important_until_to_seminar_and_news.sql
- src/test/kotlin/com/wafflestudio/csereal/core/news/NewsServiceTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/news/scheduler/NewsSchedulerTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/notice/scheduler/NoticeSchedulerTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/seminar/scheduler/SeminarSchedulerTest.kt
- src/test/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarServiceTest.kt
[Feature] Seminar/News 중요 공지 만료 기능 추가
Seminar 및 News 게시물에 중요 공지 설정 시 만료일을 지정하고, 스케줄러를 통해 만료된 공지를 자동으로 일반 공지로 전환하는 기능을 추가합니다.
이번 PR은 Seminar와 News의 '중요' 표시에 만료 기한을 설정하는 기능을 구현합니다. `importantUntil` 필드를 각 엔티티와 DTO에 추가하고, 관련 로직을 수정했습니다. 또한, 매일 새벽 특정 시간에 만료된 중요 게시물을 자동으로 일반 게시물로 전환하는 스케줄러를 각각 추가했습니다. 데이터베이스 스키마 변경 및 관련 테스트 코드도 포함되었습니다.
- [`de1614f`]: feat(db): add important_until column to seminar and news tables
- [`11a42bb`]: feat(news): add importantUntil field to NewsEntity and NewsDto
- [`8a3fa51`]: feat(seminar): add importantUntil field to SeminarEntity and SeminarDto
- [`12579a1`]: feat(news): add repository method to update expired important news
- [`38c860f`]: feat(seminar): add repository method to update expired important seminars
- [`f65fd3c`]: feat(news): add scheduler to manage …
> feat: seminar, news 중요 설정 만료일 추가
