docker-compose-local.yml, src/main/resources/application.yaml
로컬 db용 docker-compose-local.yml 파일 추가 및 application.yaml 파일 수정
터미널에서 `docker-compose -f docker-compose-local.yml up -d` 커맨드 실행
[0489be3700bcb18dbb88613c3961cc1358c6de0e]: 파일 추가 및 수정
구성원 API, db 마이그레이션
=> feat: 로컬 db용 설정

.github/workflows/deploy.yaml, Dockerfile
배포 시 spring boot profile이 적용되지 않는 문제가 있었습니다.
3f38074 Hotfix: Add arg for profile while build dockerfile
c8133e7 Hotfix: Save arg as env
=> [Hotfix] 배포 시 profile 적용 오류 해결

src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/database/StaffEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/ProfessorDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/ProfessorPageDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/SimpleProfessorDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/SimpleStaffDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/StaffDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
프론트 요구사항 반영해서 약간씩의 수정 사항이 있습니다.
[fe477b6fe55ab97b37cfff6e6900573b410a3ff7]: 이미지 uri 필드 추가, isActive 대신 status 로 변경 (객원교수)
[f150c5dde9718973ebb52c7a7956589b3f6e3b6d]: 행정직원 전체 조회 응답에서 task 삭제
[53b7298bafc8969d8c3710ceeca8a80463563a53]: 교수진 응답에 description 필드 추가
로그인
=> fix: 이미지 uri 필드 추가 및 프론트 요구사항 반영

.github/workflows/deploy.yaml, docker-compose.yml, src/main/kotlin/com/wafflestudio/csereal/common/Exceptions.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/CserealExceptionHandler.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/JwtConfig.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/RestTemplateConfig.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/database/TaskEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/user/database/UserEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/user/database/UserRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/user/service/CustomOidcUserService.kt, src/main/resources/application.yaml
스프링 시큐리티 oauth2-client 이용하여 oidc 로그인 구현하고 로컬 테스트까지 마쳤습니다. 최초 로그인 시 유저 DB에 저장하기 위해 CustomOidcUserService 구현하여 SecurityFilterChain에 넣어주었습니다. 별도 JWT를 이용하지 않고 스프링 시큐리티에서 관리하는 세션 쿠키를 사용하며 만료 시간은 2시간으로 설정하였습니다.
[f7aab99137ae90770f9e17a41368e6a2f2eac07d]: oidc 로그인 구현
[e76cad6701b8784a5b67c953d4ee16e4be4f795b]: taskentity 누락된 name 추가 
[214f8e7b9174bd5696f3f26e6709edf71ef25651]: 배포 상태 secret 관리
[4cc93e63c1795b3b9231e9038ccd97caa690ec40]: 유저 DB에 학번도 추가로 저장, openid spec 따라 userInfo 가져올때 sub claim 확인
[eae35ca8748dfac362740d2bbcd4c2b1281a8071]: 배포 테스트 위해 redirec-uri 변경
배포 상태 테스트
=> feat: oidc 로그인

src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
=> feat: CORS

src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/WebConfig.kt
=> fix: cors 추가 설정

docker-compose-local.yml, src/main/kotlin/com/wafflestudio/csereal/common/aop/Authenticated.kt, src/main/kotlin/com/wafflestudio/csereal/common/aop/SecurityAspect.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservceController.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReservationDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt, src/main/resources/application.yaml
예약 단건, 주별, 월별 조회 API 구현하였습니다. 권한 체크 코드 중복을 줄이기 위해 커스텀 어노테이션 생성하였습니다.
[1239c75c96f95bf4e0a27a7934ecabe978a57a85]: 커스텀 어노테이션 생성 및 aop 적용
[935fd9e47fc9af5fb7ae8ab053dc48f8af3266b3]: 조회 API
=> feat: 예약 조회 API

src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/ScholarshipPageResponse.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt, src/main/kotlin/com/wafflestudio/csereal/core/scholarship/api/ScholarshipController.kt, src/main/kotlin/com/wafflestudio/csereal/core/scholarship/database/ScholarshipEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/scholarship/database/ScholarshipRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/scholarship/dto/ScholarshipDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/scholarship/dto/SimpleScholarshipDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/scholarship/service/ScholarshipService.kt
장학제도 GET API 구현하고 상위 페이지에서 장학제도 리스트를 응답에 추가하였습니다.
[15befbaf31ee67aa14222f9469700dd0774b71ed]: 장학제도 개별 GET API
[89847b3643abfd7bf0676765b36e3fe12a6c180a]: 상위페이지 응답 수정
=> feat: 장학제도 GET API 및 장학제도 페이지 응답 수정

build.gradle.kts, src/main/kotlin/com/wafflestudio/csereal/common/config/CustomAuthenticationSuccessHandler.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt, src/main/kotlin/com/wafflestudio/csereal/common/properties/EndpointProperties.kt, src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt, src/main/resources/application.yaml
yml 파일에 프로파일 별 endpoint 설정 추가하고 로그인 관련 리다이렉트 엔드포인트 변경하였습니다.
[a3d7b7826bede133e4640fc829d45931753f4007]: yml 파일 설정
[2161d1afb35dc1b4370ee8dec00f0c7bcd07e740]: 리다이렉트 엔드포인트 변경
=> feat: custom metadata 설정 + 리다이렉트 엔드포인트 변경

src/main/kotlin/com/wafflestudio/csereal/core/recruit/api/RecruitController.kt, src/main/kotlin/com/wafflestudio/csereal/core/recruit/database/RecruitEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/recruit/database/RecruitRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/recruit/dto/RecruitPage.kt, src/main/kotlin/com/wafflestudio/csereal/core/recruit/service/RecruitService.kt
신임교수초빙 페이지입니다.
[1157ecda2444e8ae3e261352fe03a12d16c4c194`]: GET API
=> feat: 신임교수초빙

src/main/kotlin/com/wafflestudio/csereal/core/user/api/UserController.kt, src/main/kotlin/com/wafflestudio/csereal/core/user/dto/StaffAuthResponse.kt, src/main/kotlin/com/wafflestudio/csereal/core/user/service/UserService.kt
공지 목록 같은 일반/행정실 페이지뷰가 다른 경우에 사용 가능한 권한 체크용 API를 구현하였습니다. 
[a1a17be11d4014cdbec21f3240d29e082a698c1e]: 권한 체크 API
=> feat: 행정실 권한 체크 API

src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
=> fix: 로그아웃 엔드포인트 변경

src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt, src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/api/FileController.kt, src/main/kotlin/com/wafflestudio/csereal/core/resource/mainImage/service/MainImageService.kt, src/main/resources/application.yaml
=> fix: 파일 업로드 경로 통일

.github/workflows/build_and_test.yaml, build.gradle.kts, src/main/resources/application.yaml, src/test/kotlin/com/wafflestudio/csereal/global/config/TestConfig.kt
Test를 위한 kotest, mockk, h2 db
72fab71 Config: Add kotest, mockk, h2 db for testing.
dfab807 Config: Add test profile.
23a089b Config: Add testconfig for jpaqueryfactory.
7d2c6be CICD: Add build, test workflow
=> CI/CD: Test 설정

build.gradle.kts, src/main/kotlin/com/wafflestudio/csereal/common/utils/FixedPageRequest.kt, src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/api/NewsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/dto/NewsDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/api/NoticeController.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/api/SeminarController.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/dto/SeminarDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt, src/main/resources/application.yaml
공지사항에 적용한 것과 동일하게 이전 다음글 쿼리 및 total 쿼리 수정하였습니다. 유틸 패키지를 만들어서 FixedPageRequest를 추가하였습니다.
[7cecccdee4db4e7fc31166a5ae2d8385d8969de7]: 유틸 패키지 생성
[d9af0d2798c444aff0cea360623de42d93b9cee4]: 쿼리 수정
API 권한 설정
=> fix: 새소식 세미나 쿼리 수정

src/main/kotlin/com/wafflestudio/csereal/core/conference/database/ConferenceEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/service/MemberSearchService.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/database/LabEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchPostType.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/database/ResearchSearchRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchSearchService.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
연구 탭 통합검색을 위한 ResearchSearch Table을 생성하였고, Research 생성/수정, Lab 생성에 대하여 검색 index를 생성하도록 하였습니다.
57d9332 Feat: Add ResearchSearchEntity, and entry for conference, research, lab entity.
bb7f8a7 Feat: For research create/update, lab create, add updating researchsearch.
4cfa762 Feat: Add empty repository and service for ResearchSearch
=> Feat: 연구 탭 통합검색 위한 Table 생성.

docker-compose-backend.yml
=> Hotfix: Change mount volume.

src/main/kotlin/com/wafflestudio/csereal/common/config/MySQLDialectCustom.kt, src/main/kotlin/com/wafflestudio/csereal/common/repository/CommonRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/database/MemberSearchRepository.kt
972bafe Feat: Extract full text search template to common repository.
13a2364 Feat: Change full text search to use extracted repository.
=> Refactor: Extract Full Text Query Template to CommonRepository

src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/dto/NoticeSearchDto.kt
GET /notice 쿼리에서 필요한 column만 select 하도록 수정하였습니다.
=> fix: 필요한 column만 select

src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt, src/test/kotlin/com/wafflestudio/csereal/common/util/UtilsTest.kt
1cea031 Feat: Add utils substringAroundKeyword
abf84ef Test: Add test for Utils.kt
이를 적용한 Notice, Seminar, News 검색 결과 API 추가
=> Feat: 검색 결과에서 keyword 위치, 적절한 substring 추출 위한 method 추가

src/main/kotlin/com/wafflestudio/csereal/common/config/CustomAuthenticationSuccessHandler.kt, src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
프론트 로컬에서 테스트 하기 위해 임시로 변경했던 엔드포인트를 복구 하였습니다.
[ee9bc392bdb825b67251ff30c88ec6ac57234250]: 엔드포인트 복구
=> fix: 로그인 리다이렉트 엔드포인트

src/main/kotlin/com/wafflestudio/csereal/common/config/JacksonConfig.kt
iso 8601을 따라 LocalDateTime 필드 응답 마지막에 Z를 추가하였습니다.
[a973c2403e6877feb4d7ccffb7820478fc89ac29]: Custom Json Serializer 적용
=> feat: LocalDateTime 응답 마지막에 Z 추가

src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt
=> fix: 확장자 중복 버그

src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt
fix: false로 수정
메인에서 notice는 isPrivate이 false인것만 보내주게 했습니다
=> fix: false로 수정

src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainNoticeResponse.kt
~~테스트는 안해봤습니다. 배포해서 테스트 ㄱㄱ~~
테스트 열심히 하겠습니다 ㅠ..
=> Hotfix: Fix main page orderby exception.

src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservceController.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt, src/main/resources/application.yaml
이전 다음글에서 비공개 글까지 보여주는 문제가 있어서 수정하였습니다.
[7cc8e5b6f51272df63bf778fcf3c1f72e63408dd]: isPrivate false
=> fix: 이전 다음 글에서 비공개 글 제외

src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/main/dto/MainSlideResponse.kt
=> Feat: Add description for slide.

src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt
통합검색 정렬을 최신순으로 변경하였습니다.
6f29c25 Feat: Change total news search to sort by recent date.
6eceda1 Feat: Change notice total search to sort by createdAt.
=> Feat: 통합검색 정렬 최신순

.github/workflows/proxy.yaml, caddy/Caddyfile, docker-compose-caddy.yml
서버 ip를 제외한 곳에서의 백엔드 접속을 막았습니다.
=> CICD: Add blocking backend api except frontend.

src/main/kotlin/com/wafflestudio/csereal/core/user/database/UserEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/user/service/CustomOidcUserService.kt
기존에는 로그인 할때 스누씨 계정 그룹을 처음에만 체크하여 role을 부여했었는데 그룹이 변경될수도 있다고 판단하여 항상 판단하도록 변경하였습니다.
[c05d138b989083a8d0e379e3e44592a30b0bdb26]: fix: group
실제 스누씨 서버 연결
=> fix: group 변경 반영

src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/dto/AdmissionsDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/dto/AdmissionsRequest.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
feat: migrateAdmissions 추가
migrateAdmissions을 추가하고, 마이그레이션을 쉽게 하기 위해 admissionsRequest을 추가했습니다.
[78e5b071cf2556df99994e1e3d4cfd0c5c9f76d1]: migrateAdmissions을 추가하고, 마이그레이션을 쉽게 하기 위해 admissionsRequest을 추가했습니다.
[b0afcd5c0991dd0f50fca3547428f7d72943d9bc]: 잘못 쓴거 다시 수정했습니다
=> feat: migrateAdmissions 추가

.github/workflows/proxy.yaml
Caddy 서버 배포 workflow 잘못된 부분 수정하였습니다.
=> Hotfix: Change adding local ip `>` to `>>`

src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt
세미나에 기존 데이터 중에 speaker url이 긴 데이터가 있어서 넉넉하게 2047자로 늘렸습니다.
=> Feat: increase speakerurl

src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/res/AdmissionSearchResElem.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/type/AdmissionsMainType.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/type/AdmissionsPostType.kt, src/test/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsServiceTest.kt
725e082 Feat: Add korean, english section name.
15f7175 Feat: add searchContent column for saving index.
848ea58 Feat: Add search query repository method.
7fc5d31 Feat: Define dto of search result element.
37bc976 Feat: Add search Top Admission method, and add migrate method creating search content.
729dd7a Feat: Add search top admissions method to controller.
deb2041  Test: Add test for Admission Service.
=> Feat: Admission 검색

src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/ProfessorDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt, src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt, src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchSearchServiceTest.kt, src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchServiceTest.kt
fix: professor language 추가
professorDto에 language을 추가하였습니다.
[c327284a8767a62652420c9a363461c1ee012dfd]: professorDto에 language을 추가하였습니다.
=> fix: professor language 추가

src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/res/AdmissionSearchResBody.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/res/AdmissionSearchResElem.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
Refactor: Admission 검색 리펙터링
92cad4b Refactor: Merge queries into one.
01b59a9 Refactor: Add page search method.
4cf05e3 Refactor: Add total count.
b578dbe Refactor: change to search page or search top.
다른 부분 언어 필터링 추가, 리펙터링 (통일화)
=> Refactor: Admission 검색 리펙터링

src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt, src/main/kotlin/com/wafflestudio/csereal/core/about/dto/StudentClubDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/about/service/AboutService.kt
fix: StudentClubDto에 engName 추가
StudentClubDto에 engName 추가
[179e0357bfed79447324309d590cc44a5ca754c5]: 동아리 목록에 영어 이름을 같이 보내달라고 해서 StudentClubDto에 engName 추가해서 보냅니다 db에 괄호로 영어이름을 넣은 방식으로 구현했습니다
…코드가 마음에 안드실 수도 있지만 일단 결과는 원하는 대로 잘나옵니다
=> fix: StudentClubDto에 engName 추가

src/main/kotlin/com/wafflestudio/csereal/core/academics/api/res/AcademicsSearchResElement.kt
=> Feat: Academics 검색에 세부 타입 추가

src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/res/AdmissionSearchResElem.kt
=> Fix: Admission 검색 결과 html 안나오게 제거

src/main/kotlin/com/wafflestudio/csereal/core/academics/api/res/AcademicsSearchResElement.kt
=> Fix: Academic 검색 결과에 student type 항상 추가

src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
=> Fix: 새소식 통합 검색 누락된 join condition 추가

src/main/kotlin/com/wafflestudio/csereal/core/member/service/StaffService.kt
학부 총괄 행정직원을 맨 앞에 배치해 달라는 요청에 따라 로직 추가
최근에 추가된 Chenglin Fan 교수를 뒤로 보내달라는 요청이 있었는데, 다른 전/현직 외국인 교수들과 다르게 혼자 영어 이름으로 되어 있어서 이것만을 위한 커스텀 로직을 붙이는게 맞는지 아니면 행정실에 한글 이름(ex 쳉린 판?)을 요청할지 고민
=> feat: 행정직원 정렬 순서 변경

src/main/kotlin/com/wafflestudio/csereal/common/utils/Utils.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
교수진에서 한글 이름 우선으로 정렬하게끔 수정하였습니다.
=> feat: 한글 이름 우선순위 정렬

src/main/kotlin/com/wafflestudio/csereal/core/about/database/AboutEntity.kt
=> Fix: About Entity 누락된 "mappedBy" 값 추가

src/main/kotlin/com/wafflestudio/csereal/common/mockauth/DevAuthController.kt
prod 환경에서 mock-login api를 제거하였습니다.
Closes #233 .
=> prod에서 mock-login 삭제

src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
코드에 버그가 있어서 수정하였습니다.. 테스트 제대로 안해보고 올려서 죄송 😢
=> fix: sort professor

src/main/resources/application.yaml
Closes #231 
최대 스레드 정할때 참고한 글: https://junuuu.tistory.com/799
최대 풀 사이즈 조정할때 참고한 글: https://techblog.woowahan.com/2663/
실제 운영 환경에서 같은 이슈가 발생하면 재조정 여지 있음
=> fix: adjust max thread and pool size

src/main/kotlin/com/wafflestudio/csereal/core/reservation/database/ReservationEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/dto/ReserveRequest.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
행정실 요청사항에 따라 예약 테이블에 개인정보 동의 여부를 기록합니다.
=> feat: 개인정보 동의 여부 기록

src/main/kotlin/com/wafflestudio/csereal/core/research/service/ResearchService.kt
교수진과 마찬가지로 영어 이름 lab 뒤로 가게끔 정렬
=> fix: sort labs

.github/workflows/deploy_dev.yaml, src/main/resources/application.yaml
local, dev 환경에서는 cse-waffle-dev, prod에서는 cse-waffle-prod id 및 secret 사용
=> fix: idsnucse prod 설정 분리

src/main/kotlin/com/wafflestudio/csereal/core/about/api/AboutController.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/AdmissionsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/conference/api/ConferenceController.kt, src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/api/StaffController.kt, src/main/kotlin/com/wafflestudio/csereal/core/research/api/ResearchController.kt
Closing #249 
@Profile을 통하여 prod 환경에서 migration uri들을 비활성화하였습니다.
=> Config: Disable migrate on profile prod.

caddy/Caddyfile, src/main/kotlin/com/wafflestudio/csereal/core/main/api/MainController.kt
수정 사항이 한동안 존재할 것으로 예상되어 검색 index refresh api를 서버 로컬에서만 접근 가능하도록 수정하였습니다.
=> Feat: 검색 refresh api 로컬에서 접근 가능하도록 변경

src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt
=> fix: sort seminar

src/main/kotlin/com/wafflestudio/csereal/core/academics/dto/GeneralStudiesRequirementsPageResponse.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
행정실 요청에 따라 삭제
배포 후 DB에서도 날릴 예정
=> fix: 교양 교과과정 변경 내역 삭제

docker-compose-backend.yml, src/main/resources/application.yaml, src/main/resources/logback-spring.xml
- dev, prod 환경에서 로그가 파일로 저장되도록 하였습니다.
- 로그에 sql, servlet, security 관련 정보가 출력되도록 하였습니다.
4b92194 Config: Add async file log appender for dev, prod env
b8970f9 Config: Set log to show servlet, security, sql info for all profile.
5f0914c CICD: Mount log directory.
=> Config: 로그 파일 저장 추가, 항목 추가

src/main/kotlin/com/wafflestudio/csereal/core/reservation/api/ReservationController.kt
=> fix: subtract 9 hours to start to convert it to UTC

src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt
=> 영문 페이지 LastName 기준 정렬

src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt
=> Feat: 새소식 생성 날짜가 아닌 실제 날짜 순으로 정렬되도록 변경

src/main/kotlin/com/wafflestudio/csereal/common/controller/ContentEntityType.kt, src/main/kotlin/com/wafflestudio/csereal/core/internal/api/InternalController.kt, src/main/kotlin/com/wafflestudio/csereal/core/internal/database/InternalEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/internal/database/InternalRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/internal/dto/InternalDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/internal/service/InternalService.kt, src/test/kotlin/com/wafflestudio/csereal/core/internal/service/InternalServiceTest.kt
.internal 페이지에 대하여 db 항목 추가, GET과 PUT API를 추가하였습니다.
=> Feat: Internal GET, PUT API 추가

src/main/kotlin/com/wafflestudio/csereal/common/CserealException.kt, src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
행정실 요청에 따라 교수회의실 예약 요청시 staff 인지 체크, 아닐 시 403
=> fix: 교수회의실 예약 권한 변경

.github/workflows/proxy_dev.yaml, .gitignore, caddy/Caddyfile, caddy/Caddyfile.dev, src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt
deprecated 된 filter chain 메서드들 변경하면서 csrf disable 에 해당하는 부분 제거, dev 서버용 Caddyfile 별도 생성
[b854b614806fe211ff2a8f70c5c03f4142299adf]: spring security 수정
[210e23860675e96e643c1177621dd5a44b52f0bb]: dev Caddyfile 생성 및 워크플로우 수정
dev 배포 잘 되는지 테스트, 로그인 테스트
=> 로그인 취약점 수정 및 Caddyfile.dev 추가

src/main/kotlin/com/wafflestudio/csereal/common/config/SecurityConfig.kt, src/main/resources/application.yaml
csrf 기능을 다시 끄고, session timeout을 9시간으로, 쿠키 same-site를 lax로 설정하였습니다.
=> 스프링 세션 설정 변경

src/main/kotlin/com/wafflestudio/csereal/core/member/api/ProfessorController.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/api/req/CreateProfessorReqBody.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/api/req/ModifyProfessorReqBody.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/database/ProfessorEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/dto/ProfessorDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorService.kt, src/test/kotlin/com/wafflestudio/csereal/core/member/service/ProfessorServiceTest.kt, src/test/kotlin/com/wafflestudio/csereal/core/reseach/service/ResearchSearchServiceTest.kt
- Professor API 수정하여 적용
- 이미지 제거 로직 변경 (req body에서 이미지 제거 여부 받도록 수정)
- response body를 새로 생성, dto는 response body로만 사용되도록 수정.
=> Feat: Professor 수정 API 추가

src/main/kotlin/com/wafflestudio/csereal/core/academics/api/AcademicsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/CreateYearReq.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/api/req/UpdateYearReq.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/database/AcademicsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt
전공 이수 표준 형태, 필수 교양 과목, 교과목 변경 내역에 해당하는 CUD api
=> feat: CUD year response

src/main/kotlin/com/wafflestudio/csereal/core/member/api/v2/ProfessorController.kt
Professor Delete API에 multipart/form-data 잘못 설정한 것 제거
=> Fix: remove consume type for delete mapping.

src/main/kotlin/com/wafflestudio/csereal/core/member/api/v2/ProfessorController.kt
한 줄 수정이라서 바로 배포하겠습니다아
PR 요약해주세요
[`Commit Hash1`]: 커밋 설명1
[`Commit Hash2`]: 커밋 설명2
TODO가 있다면 작성해주시고, 없다면 생략해주세요.
=> Merge develop to main

src/main/kotlin/com/wafflestudio/csereal/core/academics/api/v2/AcademicsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/academics/service/AcademicsService.kt, src/main/resources/application.yaml
sort 파라미터를 받아서 정렬할 수 있도록 했고, 쿠키에 secure 옵션을 추가했습니다.
=> 교과목 정렬, 쿠키 secure 옵션 추가

src/main/kotlin/com/wafflestudio/csereal/core/member/api/v2/ProfessorController.kt, src/main/kotlin/com/wafflestudio/csereal/core/member/api/v2/StaffController.kt
ref: https://wafflestudio.slack.com/archives/C056KQCJHT7/p1725432129780569
=> Refactor: 구성원 POST API image => mainImage 리펙토링

src/main/kotlin/com/wafflestudio/csereal/core/research/dto/LabDto.kt
- lab GET에 사용되는 Lab Dto에 group id와 name을 포함한 LabGroupDto를 포함하도록 수정하였습니다.
- prod 배포시 프론트랑 동시에 배포
=> Feat: Lab GET에 group id 포함

.github/workflows/database_dev.yaml, .github/workflows/deploy_dev.yaml, .github/workflows/proxy_dev.yaml
dev 서버에 ssh 포트를 변경하며 이를 github action에 반영하였습니다.
=> CI: dev ssh 포트 추가

src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/req/UpdateAdmissionReq.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/res/GroupedAdmission.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/v1/AdmissionsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/api/v2/AdmissionsController.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/database/AdmissionsEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/admissions/service/AdmissionsService.kt
=> 입학 탭 v2 RU api

.gitignore, build.gradle.kts, src/main/resources/application.yaml, src/main/resources/db/migration/V1__init.sql, src/main/resources/db/migration/V2__create_council.sql
Config: Implement Flyway for db migration
- Flyway를 도입하였습니다.
- develop, production에 현재 index가 랜덤 uuid값으로 이름이 설정되어 있습니다. flyway를 적용하기 위해 배포 전 해당 index들 이름 싹 바꿔야됩니다..
=> Config: Implement Flyway for db migration

src/main/kotlin/com/wafflestudio/csereal/core/council/api/res/CouncilFileResponse.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/database/CouncilFileEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/database/CouncilFileRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/dto/CouncilFileDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/service/CouncilFileService.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/type/CouncilFileType.kt, src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/database/AttachmentEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/resource/attachment/service/AttachmentService.kt, src/main/resources/db/migration/V4__create_council_file.sql
- 학생회 파일 관련 API를 구현하였습니다.
- 첨부파일밖에 없어서 기존 api 형식과 조금 다르게 구현해보긴 했는데, 관련해서 피드백 환영합니다.
=> Feat: 학생회 파일 관련 API 구현

src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/database/CouncilRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/dto/CouncilIntroDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/dto/ReportDto.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/service/CouncilService.kt
=> CouncilIntro RU api

src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/database/CouncilFileRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/service/CouncilFileService.kt
- 추후 회의록 너무 많아지는 경우 pagination 구현 혹은 이 api 사용하지 않는 방식으로 수정
=> feat: 학생회 회의기록 전체 가져오기 API 추가 (+ 회의록 생성 시 년도 validation 추가)

src/main/kotlin/com/wafflestudio/csereal/core/council/api/req/CouncilFileModifyReq.kt, src/main/kotlin/com/wafflestudio/csereal/core/council/api/v2/CouncilController.kt
- council file 관련 api에 대하여
- deleteIds request body로 wrapping
- addFiles -> newAttachments
=> feat: councilfile api 컨벤션 따르도록 수정

caddy/Caddyfile
실제 쓰이는 api와 캐디파일에서 막는 uri를 맞추었습니다
[6f5a667]: 캐디파일 backend_denied uri 수정
=> hotfix: modify denied url in caddyfile

src/main/kotlin/com/wafflestudio/csereal/core/reservation/service/ReservationService.kt
=> block LAB reservation if not staff

src/main/kotlin/com/wafflestudio/csereal/core/admin/database/AdminRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/main/database/MainRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/database/NewsRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/news/service/NewsService.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/database/NoticeRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/notice/service/NoticeService.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarEntity.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/database/SeminarRepository.kt, src/main/kotlin/com/wafflestudio/csereal/core/seminar/service/SeminarService.kt, src/main/resources/db/migration/V11__drop_is_deleted.sql
prod db에서 is_deleted true인 row 들은 미리 삭제했습니다.
=> remove soft delete
